/*
 * Script creación:
 *create database grupoDEJAD_tienda;
 *create user 'grupoDEJAD'@'%' identified by 'grupoDEJAD';
 *grant all on grupoDEJAD_tienda.* to 'grupoDEJAD'@'%';
 * 
 * AUTOR: Luis Enrique Limones
 * GRUPO: DEJAD (Daniel, Enrique, Javier, Álvaro, Denise)
 * FEHCA: 16/01/2026
 * 
 * Descripción: Script de creacion de tablas.
 * 
 */

CREATE TABLE CLIENTES(
    ID_CLIENTE VARCHAR(10) NOT NULL,
    NOMBRE VARCHAR(25),
    APELLIDOS VARCHAR(25),
    CORREO VARCHAR(30),
    TELEFONO INT(10),
    FECHA_REGISTRO DATE,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PEDIDO(
    ID_PEDIDO VARCHAR(30) NOT NULL,
    FECHA_REALIZACION DATE,
    ESTADO VARCHAR(25),
    PRECIO_UNITARIO DECIMAL(10,2),
    CANTIDAD_SOLICITADA INT(10),
    ID_CLIENTE VARCHAR(10),
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_PEDIDO FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);
CREATE TABLE PRODUCTO(
    ID_PRODUCTO INT(10) NOT NULL,
    NOMBRE VARCHAR(25),
    PRECIO DECIMAL(10,2),
    STOCK DECIMAL(10),
    CATEGORIA VARCHAR(10),
    ID_PEDIDO VARCHAR(30) NOT NULL,
    ID_CLIENTE VARCHAR(10) NOT NULL,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT FK1_PRODUCTO FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
    CONSTRAINT FK2_PRODUCTO FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

CREATE TABLE ENVIO(
    ID_ENVIO VARCHAR(30) NOT NULL,
    DIRECCION VARCHAR(100),
    CIUDAD VARCHAR(25),
    CODIGO_POSTAL INT(10),
    FECHA_ENVIO DATE,
    FECHA_ENTREGA DATE,
    ID_PEDIDO VARCHAR(30) NOT NULL,
    CONSTRAINT PK_ENVIO PRIMARY KEY (ID_ENVIO),
    CONSTRAINT FK_ENVIO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
);

CREATE TABLE PAGOS(
    ID_PAGO VARCHAR(10) NOT NULL,
    FECHA_PAGO DATE,
    IMPORTE_PAGO DECIMAL(10,2),
    METODO_PAGO VARCHAR(25),
    ID_ENVIO VARCHAR(30) NOT NULL,
    CONSTRAINT PK_PAGOS PRIMARY KEY (ID_PAGO),
    CONSTRAINT FK_PAGOS FOREIGN KEY (ID_ENVIO) REFERENCES ENVIO (ID_ENVIO)
);
