/*
 * Script creación:
 * ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
 * create user TIENDA_DEJAD identified by TIENDA_DEJAD;
 * GRANT CONNECT, RESOURCE, DBA TO TIENDA_DEJAD;
 * 
 * AUTOR: Luis Enrique Limones
 * GRUPO: DEJAD (Daniel, Enrique, Javier, Álvaro, Denise)
 * FEHCA: 16/01/2026
 * 
 * Descripción: Script de inserción de datos y restricciones.
 * 
 */

CREATE TABLE CLIENTES(
    ID_CLIENTE VARCHAR2(10) NOT NULL,
    NOMBRE VARCHAR2(25),
    APELLIDOS VARCHAR2(25),
    CORREO VARCHAR2(30),
    TELEFONO NUMBER(10),
    FECHA_REGISTRO DATE,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PEDIDO(
    ID_PEDIDO VARCHAR2(30) NOT NULL,
    FECHA_REALIZACION DATE,
    ESTADO VARCHAR2(25),
    PRECIO_UNITARIO NUMBER(10,2),
    CANTIDAD_SOLICITADA NUMBER(10),
    ID_CLIENTE VARCHAR2(10),
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_PEDIDO FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);
CREATE TABLE PRODUCTO(
    ID_PRODUCTO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(25),
    PRECIO NUMBER(10,2),
    STOCK NUMBER(10),
    CATEGORIA VARCHAR2(10),
    ID_PEDIDO VARCHAR2(30) NOT NULL,
    ID_CLIENTE VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT FK1_PRODUCTO FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
    CONSTRAINT FK2_PRODUCTO FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

CREATE TABLE ENVIO(
    ID_ENVIO VARCHAR2(30) NOT NULL,
    DIRECCION VARCHAR2(100),
    CIUDAD VARCHAR2(25),
    CODIGO_POSTAL NUMBER(10),
    FECHA_ENVIO DATE,
    FECHA_ENTREGA DATE,
    ID_PEDIDO VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_ENVIO PRIMARY KEY (ID_ENVIO),
    CONSTRAINT FK_ENVIO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
);

CREATE TABLE PAGOS(
    ID_PAGO VARCHAR2(10) NOT NULL,
    FECHA_PAGO DATE,
    IMPORTE_PAGO NUMBER(10,2),
    METODO_PAGO VARCHAR2(25),
    ID_ENVIO VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_PAGOS PRIMARY KEY (ID_PAGO),
    CONSTRAINT FK_PAGOS FOREIGN KEY (ID_ENVIO) REFERENCES ENVIO (ID_ENVIO)
);
