-- create database trabajogrupo;
-- create user 'dummy'@'%' identified by 'dummy';
-- grant all on db_exampleName.* to 'dummy'@'%';

CREATE TABLE CLIENTES (
    ID_CLIENTE INT NOT NULL ,
    NOMBRE VARCHAR(25),
    APELLIDOS VARCHAR(25),
    CORREO VARCHAR(30),
    TELEFONO VARCHAR(15),
    FECHA_REGISTRO DATE,
    PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PRODUCTO (
    ID_PRODUCTO INT NOT NULL ,
    NOMBRE VARCHAR(25),
    PRECIO INT,
    STOCK INT,
    CATEGORIA VARCHAR(10),
    PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE PEDIDO (
    ID_PEDIDO INT NOT NULL ,
    FECHA_REALIZACION DATE,
    ESTADO VARCHAR(25),
    ID_CLIENTE INT,
    PRIMARY KEY (ID_PEDIDO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE TABLE DETALLE_PEDIDO (
    ID_PEDIDO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    PRECIO_UNITARIO INT,
    CANTIDAD_SOLICITADA INT,
    PRIMARY KEY (ID_PEDIDO, ID_PRODUCTO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE ENVIO (
    ID_ENVIO INT NOT NULL ,
    DIRECCION VARCHAR(25),
    CIUDAD VARCHAR(25),
    CODIGO_POSTAL VARCHAR(10),
    FECHA_ENVIO DATE,
    ID_PEDIDO INT NOT NULL,
    PRIMARY KEY (ID_ENVIO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
);

CREATE TABLE PAGOS (
    ID_PAGO INT NOT NULL ,
    FECHA_PAGO DATE,
    IMPORTE_PAGO DECIMAL(10,2),
    METODO_PAGO VARCHAR(25),
    ID_ENVIO INT NOT NULL,
    PRIMARY KEY (ID_PAGO),
    FOREIGN KEY (ID_ENVIO) REFERENCES ENVIO(ID_ENVIO)
);

CREATE TABLE ADQUIERE (
    ID_CLIENTE INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    PRIMARY KEY (ID_CLIENTE, ID_PRODUCTO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);


