
--ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;  
--create user PROYECTOGRUPO identified by PROYECTOGRUPO;
--GRANT CONNECT, RESOURCE, DBA TO PROYECTOGRUPO;


CREATE TABLE CLIENTES(
    ID_CLIENTE NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(25),
    APELLIDOS VARCHAR2(25),
    CORREO VARCHAR2(30),
    TELEFONO NUMBER(10),
    FECHA_REGISTRO DATE,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PRODUCTO(
    ID_PRODUCTO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(25),
    PRECIO NUMBER(10,2),
    STOCK NUMBER(10),
    CATEGORIA VARCHAR2(10),
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE PEDIDO(
    ID_PEDIDO NUMBER(10) NOT NULL,
    FECHA_REALIZACION DATE,
    ESTADO VARCHAR2(25),
    ID_CLIENTE NUMBER(10),
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK1_PEDIDO FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

CREATE TABLE DETALLE_PEDIDO(
    ID_PEDIDO NUMBER(10) NOT NULL,
    ID_PRODUCTO NUMBER(10) NOT NULL,
    PRECIO_UNITARIO NUMBER(10,2),
    CANTIDAD_SOLICITADA NUMBER(10),
    CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (ID_PEDIDO, ID_PRODUCTO),
    CONSTRAINT FK1_DETALLE_PEDIDO FOREIGN KEY(ID_PEDIDO)  REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK2_DETALLE_PEDIDO FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE ENVIO(
    ID_ENVIO NUMBER(10) NOT NULL,
    DIRECCION VARCHAR2(25),
    CIUDAD VARCHAR2(25),
    CODIGO_POSTAL NUMBER (10),
    FECHA_ENVIO DATE,
    ID_PEDIDO NUMBER(10) NOT NULL,
    CONSTRAINT PK_ENVIO PRIMARY KEY (ID_ENVIO),
    CONSTRAINT FK_ENVIO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
);

CREATE TABLE PAGOS(
    ID_PAGO NUMBER(10) NOT NULL,
    FECHA_PAGO DATE,
    IMPORTE_PAGO NUMBER(10,2),
    METODO_PAGO VARCHAR2(25),
    ID_ENVIO NUMBER(10) NOT NULL,
    CONSTRAINT PK_PAGOS PRIMARY KEY (ID_PAGO),
    CONSTRAINT FK_PAGOS FOREIGN KEY (ID_ENVIO) REFERENCES ENVIO (ID_ENVIO)
);

CREATE TABLE ADQUIERE(
    ID_CLIENTE NUMBER(10) NOT NULL,
    ID_PRODUCTO NUMBER(10) NOT NULL,
    CONSTRAINT PK_ADQUIERE PRIMARY KEY (ID_CLIENTE, ID_PRODUCTO),
    CONSTRAINT FK1_ADQUIERE FOREIGN KEY (ID_CLIENTE)  REFERENCES CLIENTES (ID_CLIENTE),
    CONSTRAINT FK2_ADQUIERE FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);









