CREATE TABLE CLIENTE
(
    ID_CLIENTE NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(30),
    APELLIDOS VARCHAR2(50),
    CORREO VARCHAR2(50),
    TELEFONO VARCHAR2(15),
    FECHA_REGISTRO DATE,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PRODUCTO
(
    ID_PRODUCTO NUMBER(10) NOT NULL ,
    NOMBRE VARCHAR2(40),
    CATEGORIA VARCHAR2(30),
    PRECIO NUMBER(10),
    STOCK NUMBER(10),
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE PEDIDO
(
    ID_PEDIDO NUMBER(10) NOT NULL,
    FECHA_REALIZACION DATE,
    ESTADO VARCHAR2(20),
    ID_CLIENTE NUMBER(10) NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK1_PEDIDO FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE DETALLE_PEDIDO
(
    ID_DETPEDIDO NUMBER(10) NOT NULL,
    ID_PRODUCTO NUMBER(10) NOT NULL,
    PRECIO_UNITARIO NUMBER(10),
    CANTIDAD_SOLICITADA NUMBER(10),
    CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (ID_DETPEDIDO, ID_PRODUCTO),
    CONSTRAINT FK1_DETALLE_PEDIDO FOREIGN KEY (ID_DETPEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK2_DETALLE_PEDIDO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE ENVIO
(
    ID_ENVIO NUMBER(10) NOT NULL,
    DIRECCION VARCHAR2(50),
    CIUDAD VARCHAR2(30),
    CODIGO_POSTAL NUMBER(5),
    FECHA_ENVIO DATE,
    FECHA_ENTREGA DATE,
    ID_PEDIDO NUMBER(10) NOT NULL,
    CONSTRAINT PK_ENVIO PRIMARY KEY (ID_ENVIO),
    CONSTRAINT FK1_ENVIO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
);

CREATE TABLE PAGO
(
    ID_PAGO NUMBER(10) NOT NULL,
    FECHA_PAGO DATE,
    IMPORTE_PAGO NUMBER(10),
    METODO_PAGO VARCHAR2(20),
    ID_ENVIO NUMBER(10) NOT NULL,
    CONSTRAINT PK_PAGO PRIMARY KEY (ID_PAGO),
    CONSTRAINT FK1_PAGO FOREIGN KEY (ID_ENVIO) REFERENCES ENVIO(ID_ENVIO)
);

CREATE TABLE ADQUIERE
(
    ID_CLIENTE NUMBER(10) NOT NULL,
    ID_PRODUCTO NUMBER(10) NOT NULL,
    CONSTRAINT PK_ADQUIERE PRIMARY KEY (ID_CLIENTE, ID_PRODUCTO),
    CONSTRAINT FK1_ADQUIERE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK2_ADQUIERE FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

