CREATE TABLE CLIENTE (
    ID_CLIENTE INT NOT NULL,
    NOMBRE VARCHAR(30),
    APELLIDOS VARCHAR(50),
    CORREO VARCHAR(50),
    TELEFONO VARCHAR(15),
    FECHA_REGISTRO DATE,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PRODUCTO (
    ID_PRODUCTO INT NOT NULL,
    NOMBRE VARCHAR(40),
    CATEGORIA VARCHAR(30),
    PRECIO DECIMAL(10,0),
    STOCK INT,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE PEDIDO (
    ID_PEDIDO INT NOT NULL,
    FECHA_REALIZACION DATE,
    ESTADO VARCHAR(20),
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK1_PEDIDO 
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE DETALLE_PEDIDO (
    ID_DETPEDIDO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,0),
    CANTIDAD_SOLICITADA INT,
    CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (ID_DETPEDIDO, ID_PRODUCTO),
    CONSTRAINT FK1_DETALLE_PEDIDO 
        FOREIGN KEY (ID_DETPEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK2_DETALLE_PEDIDO 
        FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE ENVIO (
    ID_ENVIO INT NOT NULL,
    DIRECCION VARCHAR(50),
    CIUDAD VARCHAR(30),
    CODIGO_POSTAL INT,
    FECHA_ENVIO DATE,
    FECHA_ENTREGA DATE,
    ID_PEDIDO INT NOT NULL,
    CONSTRAINT PK_ENVIO PRIMARY KEY (ID_ENVIO),
    CONSTRAINT FK1_ENVIO 
        FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO)
);

CREATE TABLE PAGO (
    ID_PAGO INT NOT NULL,
    FECHA_PAGO DATE,
    IMPORTE_PAGO DECIMAL(10,0),
    METODO_PAGO VARCHAR(20),
    ID_ENVIO INT NOT NULL,
    CONSTRAINT PK_PAGO PRIMARY KEY (ID_PAGO),
    CONSTRAINT FK1_PAGO 
        FOREIGN KEY (ID_ENVIO) REFERENCES ENVIO(ID_ENVIO)
);

CREATE TABLE ADQUIERE (
    ID_CLIENTE INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CONSTRAINT PK_ADQUIERE PRIMARY KEY (ID_CLIENTE, ID_PRODUCTO),
    CONSTRAINT FK1_ADQUIERE 
        FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK2_ADQUIERE 
        FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);
