CREATE TABLE CLIENTES
(
	ID_CLIENTE VARCHAR(20)NOT NULL,
	NOMBRE VARCHAR(25),
	APELLIDOS VARCHAR(25),
	CORREO VARCHAR(25),
	TELEFONO INT(9),
	FECHA_REGISTRO DATE,
	CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PRODUCTO
(
	ID_PRODUCTO INT(20)NOT NULL,
	NOMBRE VARCHAR(25),
	PRECIO INT(5),
	STOCK INT(4),
	CATEGORIA VARCHAR(5),
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE PEDIDO
(
	ID_PEDIDO INT(20)NOT NULL,
	FECHA_REALIZACION DATE,
	ESTADO VARCHAR(10),
	ID_CLIENTE VARCHAR(20)NOT NULL,
	CONSTRAINT PK_PEDIDO_1 PRIMARY KEY (ID_PEDIDO),
	CONSTRAINT FK_PEDIDO_2 FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

CREATE TABLE DETALLE_PEDIDO
(
	ID_PEDIDO INT(20)NOT NULL,
	ID_PRODUCTO INT(20)NOT NULL,
	PRECIO_UNITARIO INT(5),
	CANTIDAD_SOLICITADA INT(4),
	CONSTRAINT PK_DETALLE_PEDIDO_1 PRIMARY KEY (ID_PEDIDO,ID_PRODUCTO),
	CONSTRAINT FK_DETALLE_PEDIDO_2 FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
	CONSTRAINT FK_DETALLE_PEDIDO_3 FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);

CREATE TABLE ENVIO
(
	ID_ENVIO INT(20)NOT NULL,
	DIRECCION VARCHAR(25),
	CIUDAD VARCHAR(15),
	CODIGO_POSTAL INT(10),
	FECHA_ENVIO DATE,
	FECHA_ENTREGA DATE,
	ID_PEDIDO INT(20)NOT NULL,
	CONSTRAINT PK_ENVIO_1 PRIMARY KEY (ID_ENVIO),
	CONSTRAINT FK_ENVIO_2 FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
);

CREATE TABLE PAGOS
(
	ID_PAGO INT(20)NOT NULL,
	FECHA_PAGO DATE,
	IMPORTE_PAGO INT(6),
	METODO_PAGO VARCHAR(4),
	ID_ENVIO INT(20)NOT NULL,
	CONSTRAINT PK_PAGOS_1 PRIMARY KEY (ID_PAGO),
	CONSTRAINT FK_PAGOS_2 FOREIGN KEY (ID_ENVIO) REFERENCES ENVIO (ID_ENVIO)
);

CREATE TABLE ADQUIERE
(
	ID_CLIENTE VARCHAR(20)NOT NULL,
	ID_PRODUCTO INT(20)NOT NULL,
	CONSTRAINT PK_ADQUIERE_1 PRIMARY KEY (ID_CLIENTE,ID_PRODUCTO),
	CONSTRAINT FK_ADQUIERE_2 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
	CONSTRAINT FK_ADQUIERE_3 FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);