-- create database ProyectoGrupo;
-- create user 'dummy'@'%' identified by 'dummy';
-- grant all on db_exampleName.* to 'dummy'@'%';

CREATE TABLE CLIENTES(
    ID_CLIENTE INT NOT NULL,
    NOMBRE VARCHAR(15),
    APELLIDOS VARCHAR(10),
    CORREO VARCHAR(10),
    TELEFONO INT,
    FECHA_REGISTRO DATE,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PRODUCTO(
    ID_PRODUCTO INT NOT NULL,
    NOMBRE VARCHAR(15),
    PRECIO INT,
    STOCK INT,
    CATEGORIA VARCHAR(10),
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE PEDIDO(
    ID_PEDIDO INT NOT NULL,
    FECHA_REALIZACION DATE,
    ESTADO VARCHAR(10),
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

CREATE TABLE DETELLE_PEDIDO(
    ID_PEDIDO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    PRECIO_UNITARIO INT,
    CANTIDAD_SOLICITADA INT,
    CONSTRAINT PK_DETELLE_PEDIDO PRIMARY KEY (ID_PEDIDO, ID_PRODUCTO),
    CONSTRAINT FK_DETELLE_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
    CONSTRAINT FK2_DETELLE_PEDIDO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);

CREATE TABLE ENVIO(
    ID_ENVIO INT NOT NULL,
	DIRECCION VARCHAR (15),
	CIUDAD VARCHAR (10),
	CODIGO_POSTAL INT,
	FECHA_ENVIO DATE,
	FECHA_ENTREGA DATE,
	ID_PEDIDO INT NOT NULL,
    CONSTRAINT PK_ENVIO PRIMARY KEY (ID_ENVIO),
    CONSTRAINT FK_ENVIO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
);

CREATE TABLE PAGOS(
    ID_PAGO INT NOT NULL,
    FECHA_PAGO DATE,
    IMPORTE_PAGO INT,
    METODO_PAGO VARCHAR(10),
    ID_ENVIO INT NOT NULL,
    CONSTRAINT PK_PAGOS PRIMARY KEY (ID_PAGO),
    CONSTRAINT FK_PAGOS FOREIGN KEY (ID_ENVIO) REFERENCES ENVIO (ID_ENVIO)
);

CREATE TABLE ADQUIERE(
    ID_CLIENTE INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CONSTRAINT PK_ADQUIERE PRIMARY KEY (ID_CLIENTE,ID_PRODUCTO),
    CONSTRAINT FK_ADQUIERE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
    CONSTRAINT FK2_ADQUIERE FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);

