--alter session set "_oracle_script"=true;  
--create user ProyectoGrupo identified by ProyectoGrupo;
--GRANT CONNECT, RESOURCE, DBA TO ProyectoGrupo;

CREATE TABLE CLIENTES(
    ID_CLIENTE NUMBER(7) NOT NULL,
    NOMBRE VARCHAR2(15),
    APELLIDOS VARCHAR2(10),
    CORREO VARCHAR2(10),
    TELEFONO NUMBER(10),
    FECHA_REGISTRO DATE,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PRODUCTO(
    ID_PRODUCTO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(15),
    PRECIO NUMBER(10, 2),
    STOCK NUMBER (10),
    CATEGORIA VARCHAR2(10),
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE PEDIDO(
    ID_PEDIDO NUMBER (10) NOT NULL,
    FECHA_REALIZACION DATE,
    ESTADO VARCHAR2(10),
    ID_CLIENTE NUMBER (10) NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

CREATE TABLE DETELLE_PEDIDO(
    ID_PEDIDO NUMBER (10) NOT NULL,
    ID_PRODUCTO NUMBER (10) NOT NULL,
    PRECIO_UNITARIO NUMBER (10, 2),
    CANTIDAD_SOLICITADA NUMBER (10),
    CONSTRAINT PK_DETELLE_PEDIDO PRIMARY KEY (ID_PEDIDO, ID_PRODUCTO),
    CONSTRAINT FK_DETELLE_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO),
    CONSTRAINT FK2_DETELLE_PEDIDO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);

CREATE TABLE ENVIO(
    ID_ENVIO NUMBER (10) NOT NULL,
	DIRECCION VARCHAR2 (15),
	CIUDAD VARCHAR2 (10),
	CODIGO_POSTAL NUMBER (10),
	FECHA_ENVIO DATE,
	FECHA_ENTREGA DATE,
	ID_PEDIDO NUMBER (10) NOT NULL,
    CONSTRAINT PK_ENVIO PRIMARY KEY (ID_ENVIO),
    CONSTRAINT FK_ENVIO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO (ID_PEDIDO)
);

CREATE TABLE PAGOS(
    ID_PAGO NUMBER(10) NOT NULL,
    FECHA_PAGO DATE,
    IMPORTE_PAGO NUMBER(10, 2),
    METODO_PAGO VARCHAR2(10),
    ID_ENVIO NUMBER(10) NOT NULL,
    CONSTRAINT PK_PAGOS PRIMARY KEY (ID_PAGO),
    CONSTRAINT FK_PAGOS FOREIGN KEY (ID_ENVIO) REFERENCES ENVIO (ID_ENVIO)
);

CREATE TABLE ADQUIERE(
    ID_CLIENTE NUMBER(10) NOT NULL,
    ID_PRODUCTO NUMBER(10) NOT NULL,
    CONSTRAINT PK_ADQUIERE PRIMARY KEY (ID_CLIENTE,ID_PRODUCTO),
    CONSTRAINT FK_ADQUIERE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
    CONSTRAINT FK2_ADQUIERE FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);

